### PR TITLE
Made `VideoFrameBuffer` destructor public

### PR DESCRIPTION
**Pull request by Enyium**
See #314.

Did I break anything?

### CODE REVIEW

**Comment by pinterf** [comment]
Probably not. But when did you get such message? Is it for support your rust-friendly Avisynth core version?
"_. . . to prevent compiler errors downstream when calling non-const member functions_"

**Comment by Enyium** [comment]
> Is it for support your rust-friendly Avisynth core version?

Yes.

> Probably not. But when did you get such message?

It must have something to do with C++'s `std::unique_ptr`, which is mirrored by [CXX](https://cxx.rs/)'s [`UniquePtr`](https://docs.rs/cxx/latest/cxx/struct.UniquePtr.html). It seems to be just a formal barrier, since there shouldn't really be any `std::unique_ptr<VideoFrameBuffer>` created.

I get the following MSVC compiler error:

```
frame_bridge.rs.cc
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\memory(3106): error C2248: 'VideoFrameBuffer::~VideoFrameBuffer': cannot access protected member declared in class 'VideoFrameBuffer'
C:\Program Files (x86)\AviSynth+\FilterSDK\include\avisynth.h(908): note: compiler has generated 'VideoFrameBuffer::~VideoFrameBuffer' here
C:\Program Files (x86)\AviSynth+\FilterSDK\include\avisynth.h(877): note: see declaration of 'VideoFrameBuffer'
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\memory(3104): note: while compiling class template member function 'void std::default_delete<VideoFrameBuffer>::operator ()(_Ty *) noexcept const'
        with
        [
            _Ty=VideoFrameBuffer
        ]
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\memory(3217): note: see reference to function template instantiation 'void std::default_delete<VideoFrameBuffer>::operator ()(_Ty *) noexcept const' being compiled
        with
        [
            _Ty=VideoFrameBuffer
        ]
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\memory(3141): note: see reference to class template instantiation 'std::default_delete<VideoFrameBuffer>' being compiled
C:\...\target\debug\build\...\out\cxxbridge\sources\...\src\clip\frame_bridge.rs.cc(146): note: see reference to class template instantiation 'std::unique_ptr<VideoFrameBuffer,std::default_delete<VideoFrameBuffer>>' being compiled
```

**Comment by pinterf** [comment]
Then this is really the same issue as with the others? As the comments say
"_Damn compiler won't allow taking the address of reserved constructs, make a dummy interlude_"?

**Comment by Enyium** [comment]
No, the problem was that the destructor was `protected`. But, as the code implies, the AVS linkage concept, where we get addresses of everything, can't work for "reserved contructs" like destructors without the extra layer of an additional function, in this case `DESTRUCTOR()`.

**Comment by pinterf** [comment]
This one does not change existing usage, just extends the IScriptEnvironment interface in a compatible way.
If development things get settled, we must finally step the interface version as well, but let's wait for other changes with this task.

**Pull request merged**
