### PR TITLE
convert_planar.cpp: Refactor code.

### PR DESCRIPTION
**Pull request by chikuzen**

### CODE REVIEW

**Comment by pylorak** [comment]
hi Chikuzen! it seems to me at some places you removed the non-mod8/non-mod16 handling? is that correct? the default row-alignment might be large enough, but there are some source filters that force a smaller alignment,

**Comment by chikuzen** [comment]
>but there are some source filters that force a smaller alignment,
oh...
I didn't know that such troublesome filter was still surviving.
Then please reject this PR.

btw, which filter is that?

**Comment by chikuzen** [comment]
And one question.
There are many codes that asummed src_pitch is always mod16 (using _mm_load_si128).
But that is not checked.
e.g. https://github.com/AviSynth/AviSynthPlus/blob/MT/avs_core/convert/convert_planar.cpp#L206

Is it guaranteed that the size of pitch is mod16?

**Comment by pylorak** [comment]
> btw, which filter is that?
There might be others too, but in the core AviSource(), and if you do not force 4-byte alignment for it, it breaks with corrupted output. With an additional copy you could make AviSource output higher-aligned frames, but I have no guarantee that there is no other filter which also forces a small alignment.

> There are many codes that asummed src_pitch is always mod16 (using _mm_load_si128). But that is not checked. ... Is it guaranteed that the size of pitch is mod16?
It is checked. You need to look at the call site: https://github.com/AviSynth/AviSynthPlus/blob/MT/avs_core/convert/convert_planar.cpp#L499
So in this case, yes it is guaranteed.
 But that is not checked.

**Comment by chikuzen** [comment]
>AVISource()

It's not avs+'s AVISource but avisynth's AVISource, isn't it?

>It is checked.

It checked only the address of first row.
If src_pitch is not mod16 but mod 8, the filter will crash at the 2nd row even if 1st row is aligned 16byte.
I asked you about the basis by which pitch is mod16. not address.

**Comment by pylorak** [comment]
> It's not avs+'s AVISource but avisynth's AVISource, isn't it?

Avs+'s too, There was a commit a few years ago where I tried to remove it from AVISource, but then I had to add it back or otherwise its output was corrupted. https://github.com/AviSynth/AviSynthPlus/commit/0abf03d46bcf4b054c1145a95c6656aaca4eea91

> It checked only the address of first row.

Right, both should be checked, start address and pitch, so I take back what I said in my previous comment. I was confused there for a second, because AviSynth makes an implicit guarantee that the start address of any row is at least as high as the start address of the first row. But of course you cannot check the requested alignment.

**Comment by chikuzen** [comment]
>Avs+'s too,

I thought AVISource outputs 32byte aligned frames with AdjustFrameAlignment().

**Comment by pylorak** [comment]
Ok, don't rewrite the patches, I think they'll be fine as they are now. I'll pull them, and should any problems pop up, they can always be address  later as needed.

**Comment by chikuzen** [comment]
I'll send a PR to disable negative align.

**Pull request merged**
