### PR TITLE
Added `AVSValue::GetType`

### PR DESCRIPTION
**Pull request by Enyium**
See #314.

In `class AVSValue` in `avisynth.h`, I had to write

```cpp
  AvsValueType GetType() const AVS_BakedCode( return AVS_LinkCallOptDefault(AVSValue_GetType, VALUE_TYPE_UNDEFINED) )
```

instead of

```cpp
  AvsValueType GetType() const AVS_BakedCode( return AVS_LinkCall(AVSValue_GetType) )
```

to get it to work. Same as with `PDevice::GetType()`. I don't know if it's the only way to do it.

### CODE REVIEW

**Comment by pinterf** [comment]
Strongly typed enums are perfectly fine only for c++11 and above.
I don't know whether current avisynth.h requires at least c++11? Can it be a breaking issue out there among plugin developers?

**Comment by Enyium** [comment]
Let's not risk it. I removed ` : short` from the enum.

**Comment by Enyium** [comment]
Forgot changelog entry. Added issue reference also to previously added changelog entries.

**Comment by Enyium** [comment]
Closes #314.

**Comment by pinterf** [comment]
Yes, let's not risk it.
I'm quite sure though that no one would complain for it. Who is actually using these avisynth headers is probably well beyond Visual Studio 2008.

**Pull request merged**
