### PR TITLE
Fix some trivial gcc build warnings

### PR DESCRIPTION
**Pull request by wangqr**

### CODE REVIEW

**Comment by qyot27** [comment]
To help cut down on extraneous changes in any commits going forward, I pushed up a change that removes all trailing whitespace, around the time this pull request was opened.  That's causing a few minor conflicts.

**Comment by wangqr** [comment]
Nevermind. I've rebased the PR

**Comment by pinterf** [comment]
Thanks, I'd like to ask patience on making further cosmetic changes. The code is under heavy reconstruction, some changes you can see here: https://github.com/pinterf/AviSynthPlus. Bugfixes, features, I have to cherrypick and solving conflicts day long in order to apply changes from an already rewritten but at some part still two years old codebase. These changes are introducing and will introduce ugly and seems-to-be-illogical source parts temporarily that I'll cleanup.

**Comment by wangqr** [comment]
> Thanks, I'd like to ask patience on making further cosmetic changes. The code is under heavy reconstruction

I was just planning to open another PR https://github.com/wangqr/AviSynthPlus/tree/implement-physical-cpu . In that case I'll leave it there for now, you may cherry-pick it when you have time.

**Comment by qyot27** [comment]
The whitespace fix was really the only thing, because it seems to keep coming back periodically and end up sneaking into unrelated commits.

**Comment by wangqr** [comment]
> The whitespace fix was really the only thing, because it seems to keep coming back periodically and end up sneaking into unrelated commits.

This can be resolved by adding a [`.editorconfig`](https://editorconfig.org/) in the root directory, with
```
root = true
[*]
trim_trailing_whitespace = true
```

**Comment by pinterf** [comment]
> 
> 
> > Thanks, I'd like to ask patience on making further cosmetic changes. The code is under heavy reconstruction
> 
> I was just planning to open another PR from https://github.com/wangqr/AviSynthPlus/tree/implement-physical-cpu . In that case I'll leave it there for now, you may cherry-pick it when you have time.

Thanks, till then you can open an issue to have your ideas a proper place to discuss.

**Comment by qyot27** [comment]
>This can be resolved by adding a .editorconfig in the root directory

I didn't mean trailing whitespace being introduced (although that is important to prevent), I meant existing cases of it being fixed/removed amidst other changes that have nothing to do with it.

**Comment by qyot27** [comment]
This PR was adapted onto the top of the neo and arm branches and merged as part of 3.6.0, along with the physical-cpu commit referenced above.

**Pull request closed without merging**
