### PR TITLE
Conversion of English documentation to RST

### PR DESCRIPTION
**Pull request by qyot27**
After a little more than a month, it's finally done.  Style should be reasonably consistent internally.

I probably (almost certainly) won't be doing any of the other languages, simply because I found that there were technical issues to overcome that native speakers of those languages would be better able to handle.  My worknotes on style and conversion methodology are stored in distrib/rst_migration_notes.txt, and explains these technical issues I mentioned a bit more thoroughly.

The content of the FilterSDK and English docs have not been updated, since that's not a task for RST conversion - that should be done in general doc updates (this includes links that may point to dead addresses - the original docs wouldn't work for those either).  Any minor changes of the content were almost always so that it would be okay with RST syntax, or may have been otherwise cosmetic to help improve readability (the Changelog/Version history lists were all changed to grid tables).  There may have been one or two really weird and irrelevant lines in a couple files that I deleted during the process - I think they were saying something about 'plugin autoloading doesn't exist at all'.

In the meanwhile, backups of all the HTML docs are stored in docs/htm, so that the other languages can be converted to RST at a later time without compromising the existing HTML docs.

The one single issue that remains is that I haven't looked at which files need which CSS stylesheets, which is important for using rst2html to convert them back to HTML docs.  But seeing as how that is generally more relevant for Linux (and would need updates to CMakeLists and whatnot to detect Python and docutils), and that the original English HTML docs are still available in the source tree in docs/htm, this isn't so big of a deal.  The vast, vast majority of the work is already done.

### CODE REVIEW

**Comment by pylorak** [comment]
Hi! What's the state of the rst'ification? Is it good enough to ship? Also, how easy/hard is it to update it if AviSynth updates its html docs? If it is mature enough, I'd be more than interested to include it in the upcoming build.

**Comment by qyot27** [comment]
I just started working on getting it up-to-speed with the comments you left before, which is what the string of new commits are.  I'll probably squash the Sphinx-specific ones into a more logical structure when I'm done with them.

Currently, I've added the basic Sphinx stuff, added a .gitignore file, and I restructured the doctree into a form that's a bit more logical and allows for a simpler-looking front page (Overview is the start page now).  I also fixed up all the cross-doc anchor references (:ref:), and am now working on going through and getting the normal cross-doc linkage (:doc:) ready.

Since Wilbert seemed like he was going to remove the externalfilters docs from upstream, I'm not going to touch them until the end.  I'll probably trim them out and put them in a separate repository, since I took the time to actually put them into RST back in December 2013, and if need be, those versions could be used by the plugins themselves if their source ever appears on Github.  The externalplugins direction page can be updated with links to their pages on avisynth.nl, although for the time being I just made it work with the Sphinx tree.

I'm not sure what the issue with the nested bullet lists mentioned before was, though.  The examples in RST documentation were what I followed, and the Sphinx documentation looks like it keeps it the same.

If AviSynth's docs are updated, I've figured out a method that should allow the RST docs to be updated fairly easily:
- On AviSynth's side, render the touched html docs to plaintext with lynx on either side of a changed commit.
- Git diff the plaintexted docs.
- Transplant the changes into AviSynth+'s RST docs, comparing against the AviSynth's HEAD versions to make sure stuff like bold, italic, hyperlinks, etc. are handled correctly.

I haven't yet converted the changes from the RC1 commits into the rstification branch; I figured I'd do that after getting all the Sphinx fixes done.

**Comment by pylorak** [comment]
Yea, moving out the parts about external filters is fine by me. AviSynth+ should just replace it with a link to the filter list on the wiki.

**Comment by qyot27** [comment]
Current status:

- The externalfilters/ directory has been removed.  The files are archived at https://github.com/qyot27/avisynthdoc_externalfilters.  Accordingly, the externalplugins page in the docs is a short description and a link to avisynth.nl's 'External filters' page.
- The FilterSDK docs directory has been moved into the main docs source tree so that everything can be built by Sphinx at once.  If we want to preserve the curent post-install folder structure I'll have to fix a couple of links the FilterSDK contains to other docs.

Except for the RC1 changes that I'll be getting done in the next couple days or so, the main part is done, as far as I can tell.

**Comment by pylorak** [comment]
Hi,
I compiled the newest version and browsed around a bit. Looks pretty damn fine to me :)

**Comment by qyot27** [comment]
I think it should be polished enough now for inclusion.  Finally.

I became aware of an issue with Sphinx's theme settings this morning, in that the 'default' (Python docs-like) theme is now known as 'classic' in 1.3, and 1.3's default is 'alabaster', which I don't really like.  Another very clean-looking and attractive theme, 'bizstyle', was introduced in 1.3.  So it's set up to use bizstyle if Sphinx 1.3 is used, but on Sphinx 1.2 and earlier, it uses the old Python-like default.

The reason this is such an issue is, looking ahead to getting things building on Linux, not all repositories have updated versions of Sphinx (Ubuntu is still on 1.2.x, even for 15.04).  In such cases, the user would be forced to install Sphinx through pip just to be able to build the docs, so having the 1.2 fallback is more convenient.

**Comment by qyot27** [comment]
And the version number can be easily bumped in conf.py if this goes in for the release of 0.2.

**Comment by pylorak** [comment]
Merged in. This will become the new default docs in the installer, and will also be available online on avs-plus.net. For future changes to the docs, please open a new PR after pulling the repository from me.

**Pull request closed without merging**
