### PR TITLE
Add option for only install the Headers through cmake

### PR DESCRIPTION
**Pull request by sl1pkn07**
With `-DINSTALL_ONLY_HEADERS=ON` the makefile only install the headers in `${CMAKE_INSTALL_INCLUDEDIR}`
(by default /usr/local/headers), this path can be changed by `-DCMAKE_INSTALL_PREFIX` and `-DCMAKE_INSTALL_INCLUDEDIR`

this is OFF by default, and not need pass the option for build AviSynth+ as always.

GNUmakefile script is keeped only for just in case

### CODE REVIEW

**Comment by sl1pkn07** [comment]
as note, the target `uninstall` remove the files, but not the folder. this is not the correct behavior, rigth?

greetings

**Comment by qyot27** [comment]
It shouldn't be rewriting the whole file like that.  Is it changing line endings or something?

**Comment by sl1pkn07** [comment]
only ident

**Comment by qyot27** [comment]
Oh, okay.  I see it now.

RE: uninstall, as noted in the [https://github.com/AviSynth/AviSynthPlus/commit/e62e5f6ff0920bd1f030d252b08cea8327552f87](commit), it was copy-pasted from CMake's own examples on their Wiki.  I'm guessing the reason it doesn't delete the directory is because the install_manifest.txt doesn't have a separate entry for creating said directory, and that's what uninstall uses to run the removal command.

**Comment by sl1pkn07** [comment]
seems the uninstaller is a quite dangerous

i pass

**Comment by qyot27** [comment]
Committed from a cherry-pick with some changes added afterward.

To reduce confusion with the variables in CMakeLists and because the configuration step doesn't install anything, the option for users to pass was shortened to -DHEADERS_ONLY.  The install location was slightly modified, and README.md was updated.

**Pull request closed without merging**
