### PR TITLE
Minor docs updates

### PR DESCRIPTION
**Pull request by qyot27**
Merges in the few docs changes in 2.6.1's CVS, adds a couple new guides for AviSynth+, and bumps the year to 2016 and version number to 0.2 in the docs in anticipation for the next stable release.

### CODE REVIEW

**Comment by pylorak** [comment]
"version number to 0.2 in the docs in anticipation for the next stable release"
no pressure, ha? :smile:

**Comment by qyot27** [comment]
>"version number to 0.2 in the docs in anticipation for the next stable release"
no pressure, ha? :smile:

Of course not.

Actually, I've been thinking that a good way of handling the docs would be to bump the version to the next stable immediately after the previous release, because any new changes documented there wouldn't actually show up until the next stable.  Or have it as '0.3-dev' or something, and only drop the -dev when it goes stable (although that's kind of predicated on having bugfix branches for older releases).

**Comment by pylorak** [comment]
yeah but you can only do this assuming you know what the next stable version number will be. current situation is perfect example, as i've been thinking recently i'm not sure i want to call the next version 0.2, given all the updates. a similar but another example would be, if your current version is 4.0, can you tell in advance if the next version will be 5, 4.1, or 4.0.1?

**Comment by Reel-Deal** [comment]
qyot27, there's a typo in the compilation guide. Line 23 should be "...Wine currently does not **work with** binaries built with VS2015."

**Comment by qyot27** [comment]
Well, whatever the project determines to define as the meanings of the version numbers, and whatever criteria for how to determine a new version should be made.  Is it semantic versioning, with major numbers on big API bumps, or something else?  I mean, if we get to a hypothetical 0.4, we could jump right to 1.0 if IScriptEnv2 stabilizes, and there would be no 0.5-0.9.  Just as an example.  Or it could be something else entirely, like doing a stable release every X number of months if there's no show-stopping bugs, with the version number being reflective of the date rather than something intrinsic in the code.  Ubuntu and 7zip do it this way.

Whatever it happens to be, as long as it stays consistent, it would be easy to predict.

>qyot27, there's a typo in the compilation guide. Line 23 should be "...Wine currently does not work with binaries built with VS2015."

Ack.  Just goes to show no proofcheck is ever thorough enough.

**Pull request merged**
