### PR TITLE
new AVX2 routines, cleanup, Vsprintf va_list issue

### PR DESCRIPTION
**Pull request by pinterf**

### CODE REVIEW

**Comment by qyot27** [comment]
Error building on Ubuntu 19.10:
```
[  2%] Building CXX object avs_core/CMakeFiles/AvsCore.dir/convert/convert_audio.cpp.o
In file included from /home/qyot27/AviSynthPlus/avs_core/convert/convert_audio.cpp:39:
/home/qyot27/AviSynthPlus/avs_core/include/avisynth.h:1202:53: error: ‘va_list’ has not been declared
 1202 |   virtual char* __stdcall VSprintf(const char* fmt, va_list val) = 0;
      |                                                     ^~~~~~~
make[2]: *** [avs_core/CMakeFiles/AvsCore.dir/build.make:76: avs_core/CMakeFiles/AvsCore.dir/convert/convert_audio.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:156: avs_core/CMakeFiles/AvsCore.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

This can be resolved by adding <cstdarg> and <stdarg.h> into the cplusplus ifdef in include/avs/types.h:
```
#ifdef __cplusplus
  #include <cstddef>
  #include <cstdarg>
#else
  #include <stddef.h>
  #include <stdarg.h>
#endif
```

However, it still doesn't resolve the original va_list-related error in avisynth.cpp, so `-fpermissive` is still necessary:
```
[27/81] Building CXX object avs_core/CMakeFiles/AvsCore.dir/core/avisynth.cpp.o
FAILED: avs_core/CMakeFiles/AvsCore.dir/core/avisynth.cpp.o 
/usr/bin/c++  -DAvsCore_EXPORTS -DBUILDING_AVSCORE -I../avs_core/include -Iavs_core -msse2  -Wl,--no-undefined -fPIC   -std=c++17 -MD -MT avs_core/CMakeFiles/AvsCore.dir/core/avisynth.cpp.o -MF avs_core/CMakeFiles/AvsCore.dir/core/avisynth.cpp.o.d -o avs_core/CMakeFiles/AvsCore.dir/core/avisynth.cpp.o -c ../avs_core/core/avisynth.cpp
../avs_core/core/avisynth.cpp: In member function ‘virtual char* ScriptEnvironment::VSprintf(const char*, __va_list_tag*)’:
../avs_core/core/avisynth.cpp:3137:50: error: ISO C++ forbids casting to an array type ‘va_list’ {aka ‘__va_list_tag [1]’} [-fpermissive]
 3137 |     std::string str = FormatString(fmt, (va_list)val);
      |                                                  ^~~
[34/81] Building CXX object avs_core/C...s/AvsCore.dir/core/parser/script.cpp.o
ninja: build stopped: subcommand failed.
```

Two results I got by Googling the exact error message:
https://stackoverflow.com/questions/45195779/c-passing-variable-number-of-locations-from-a-given-array-to-a-function
https://github.com/ElektraInitiative/libelektra/issues/42

I don't know if those can shed some light on it or not, though.

**Comment by pinterf** [comment]
Thanks, now it is O.K. on my Ubuntu (sorry for the extra test loop, I have run a build on Ubuntu and compiled well - no wonder, I've done it in an old working folder)

**Comment by pinterf** [comment]
Made some refinements on the memory info area.
Memory limiting works like on Windows (hopefully).
Could not test OSX and BSD though.

For a computer with 16GB RAM, 64 bit Ubuntu 19.10

No SetMemoryMax, where default max request is 4GB on x64:
```
      requested= 4072 MB
      physical_memory= 16291 MB
      total_available= 7640 MB
      mem_limit= 7640 MB
      mem_sysreserve= 1024 MB
      allowed_memory= 4072 MB

```    
Using SetMemoryMax(10000)
```
      requested= 10000 MB
      physical_memory= 16291 MB
      total_available= 7667 MB
      mem_limit= 7667 MB
      mem_sysreserve= 1024 MB
      allowed_memory= 6643 MB

```

**Comment by qyot27** [comment]
I'll have to check this tonight, but I was seeing some nasty lag upon trying to load 4K video with FFMS2, and I wonder if the memory stuff would improve that.

**Comment by pinterf** [comment]
Isn't the lag because of the usual indexing procedure?

**Comment by qyot27** [comment]
I always use ffmsindex to create the index first.  This was unambiguously about loading the existing index and starting playback.  Unless it's something about 19.10 itself, as I also noticed that [Barrier](https://github.com/debauchee/barrier) takes a lot longer to start up since I upgraded (well, fresh installed) the OS.

**Comment by qyot27** [comment]
Testing the new patches, I can confirm they build on macOS/BSD once you fix them a bit¹, although since I run both of them in VMs I don't know how representative actually testing SetMemoryMax would be.

¹they're both missing declarations for memorySize and memory @ lines 909,911,915,917 in avisynth.cpp.  It should be:
```
size_t len, memorySize;
...
int64_t memsize, memory;
```

**Comment by pinterf** [comment]
Thanks, declarations were O.K. but used an previous name. Btw, is there a way to test macOS/BSD syntax on Ubuntu?

**Comment by pinterf** [comment]
Probably I'll make an option for Info() displaying memory and OS related data as well, any more idea what other useful data would help us?

**Comment by qyot27** [comment]
>Thanks, declarations were O.K. but used an previous name. Btw, is there a way to test macOS/BSD syntax on Ubuntu?

Not that I know of offhand.  I couldn't even find information on cross-compiling for them from a Linux host, which is why I just set them up through VirtualBox.

>Probably I'll make an option for Info() displaying memory and OS related data as well, any more idea what other useful data would help us?

Not really.  Especially if [SysInfo](https://forum.doom9.org/showthread.php?t=176131) gets ported to Linux.

**Pull request merged**
