### PR TITLE
Integrate changes from 2.6 RC1

### PR DESCRIPTION
**Pull request by qyot27**
Since 2.6 RC1 was released a couple months ago, I decided to look into what could be merged.  The one thing I knew needed merging (and what motivated me to attempt it in the first place) was that RC1 finally merged the 2.6-ified C interface (and thankfully, without fucking up the license like what happened with the C++ header).

The summary of notes I took while comparing the patches:
```
rejected-0	0003-Bump-revision.patch
rejected-1	0008-Change-CPUF_SSE4_2-to-0x1000-to-match-VirtualDub..patch
rejected-2	0011-Improve-reporting-of-Module-not-found-and-Proc-not-f.patch
rejected-3	0010-Only-define-KSDATAFORMAT_SUBTYPE_-if-absent.-Minor-r.patch

applies	0022-Make-I420-a-separate-type.patch

partial-1	0014-Bump-to-rev-6.-Change-CPUF_SSE4_2-to-0x1000-to-match.patch
partial-2	0013-Add-more-info-to-out-of-memory-message.-Add-IScriptE.patch
applies-1,partial-3	0005-Fix-handling-of-padded-planar-handling-on-pixel-type.patch

adapted	0004-Fix-handling-of-padded-planar-handling-on-pixel-type.patch
adapted	0006-Start-adding-2.6-functions-to-the-C-interface.patch
adapted	0007-Remove-legacy-2.5-cache-definitions-from-Avisynth.h.patch
adapted	0009-Catch-chroma-references-of-Y8-in-conditional-functio.patch
adapted	0012-Fix-VideoInfo-Is-property-to-reference-image_type.-F.patch
adapted	0017-VTrack-ATrack-avisource-Wilbert.patch
adapted	0021-Move-more-C-interface-baked-code-into-core.patch

HTML	0001-adding-new-api-documentation.patch
HTML	0002-add-new-api-documentation.patch
HTML	0015-Wrap-loooooong-lines.patch
HTML	0016-Wrap-loooooong-lines.patch
HTML	0018-2.6-updates.patch
HTML	0019-corrections.patch
HTML	0020-Repair-html-source-white-spacing-and-wraping.-Some-c.patch

rejected-0	avsplus' versioning starts from 0.x, and this should
		finally reflect that, so a different patch was used

rejected-1	avsplus has a completely rewritten CPU detection,
		already supports 0x1000 for SSE4.2

rejected-2	avsplus has a completely rewritten plugin loader

rejected-3	Most of this commit was one of: whitespace changes/cosmetics,
		irrelevant because avsplus rewrote a lot of it, or
		minor refactoring that would need to be parsed away from the avsplus-side
		changes in function/variable names and whatnot.  The KSDATAFORMAT ifndef
		was already added to avsplus.

partial-1	avsplus already supports 64-bit, so a lot of this
		(especially the extraneous line formatting) is probably irrelevant,
		also see rejected-1; the version bumping is the important thing to look at

partial-2	GetVarDef is one of a group of several similar functions that seem to be gone in
		avsplus, so don't bother with it.  LinkedVideoBuffer seems to be part of
		the stuff that got axed in avsplus, most likely with the cache improvements.
		Some of the int->size_t instances seemed to be okay, but others
		were embedded in the middle of the rewritten caches, so I left them
		alone.  I figure those caches were rewritten with int in mind anyway,
		and since avsplus does already support 64-bit, that would seem to be minor/insignificant.

applies-1	As long as the directshow_source.rc reference is removed
		why is directshow_source.rc gone from the avsplus source tree?

partial-3	See applies-1, but also required commenting out a line in directshow_source.cpp due to a redefinition error

HTML		These were all HTML commits, and commit cleanly just so long as
		the paths get adjusted to point at the correct docs locations.
```

There are a few things I still have questions about:
The AVS_ScriptEnvironment struct works only if it's in avisynth_c.h - moving it to avisynth_c.cpp caused both avisynth_c.cpp to fail compilation but also PluginManager.cpp to not compile.  I moved that piece back into the header, but if there's a way to make it work from the *.cpp the way that would seem 'better', I guess.

It seems that when avs_is_writable was moved out of avisynth_c.h, more code was added to it, but this code causes a compilation error.  I commented it out and used the version as it was from the header.

That NV12 line in directshow_source.cpp causes a compilation failure via redefinition error.  Again, I commented it out, but that would need fixing.

RC1 moves lots of cases of int to size_t in preparation for 64-bit (and unfortunately, does so mixed inside of other commits).  I figured that these weren't immediately relevant to avsplus, since we already support 64-bit.  But if those should be moved over to size_t, then let me know.

I also posted a test build in the Doom9 thread:
http://forum.doom9.org/showthread.php?p=1711770#post1711770

### CODE REVIEW

**Comment by pylorak** [comment]
I'm really starting to feel bad for not spending time on avs+ lately and not so lately. But this is a reeaally nice PR. And while pulling it, might as well look at the other stuff too.

**Comment by qyot27** [comment]
In honesty, one of the other reasons I did this was in hopes that it might help un-hiatus the project.

Apart from this pull request, I've also been working [slowly] on getting the intrinsics split into discrete files for the linux branch, although I've got no ETA on that (and I'll need to find some solution of paring down the includes on the new files, since I doubt they need all the same stuff the main one does - my solution thus far was to put them in the forward declaration headers).  The convert/ directory is more or less finished, I'm working on filters/ right now.

And I also stumbled upon a potentially better method of migrating HTML to RST, so I might actually start working on getting the non-English documentation converted over to RST too (although it'll probably wait until after the intrinsics splitting is done).

**Comment by pylorak** [comment]
OMG, didn't you merge with upstream's history before you submitted your PR? Like pulling/merging from JEEB? I noticed this too late, and now it will be a real pain to keep up with upstream, even with the tinyest modifications arrrrrghh...

**Comment by pylorak** [comment]
ok, found an easy way solve this, using git's "--strategy=ours", but please don't do this again.

**Comment by qyot27** [comment]
I'd never actually had to deal with a situation like this before, so I wasn't aware it was needed (although I'd been wondering how that aspect of history works).  Noted.

**Pull request merged**
